services:
- type: web
  name: telegram-credit-bot
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn -w 1 -k gevent -b 0.0.0.0:${PORT} bot:app_flask
  envVars:
  - key: PYTHON_VERSION
    value: 3.12
  - key: TELEGRAM_TOKEN
    sync: false
